apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-words
  labels:
    app: reverse-words
spec:
  template:
    spec:
      containers:
      - name: reverse-words
        image: quay.io/rh_ee_pknight/app:production
        env:
        - name: RELEASE
          value: "Production release"
        - $patch: replace